-- Canonical NPMS variables, runtime settings, and source-parser definitions.
-- This is the single source of truth for values consumed by Python and the UI.

INSERT INTO pms_engine_settings(setting_key,value_numeric,value_text,unit,description) VALUES
('iri_good_upper',3.5,NULL,'m/km','Upper IRI bound for Good condition'),
('iri_fair_upper',6.5,NULL,'m/km','Upper IRI bound for Fair condition'),
('iri_poor_upper',9.0,NULL,'m/km','Upper IRI bound for Poor condition'),
('reporting_date',NULL,'2026-12-31','date','Current reporting date'),
('ml_hidden_layers',NULL,'128,96,64,32','neurons','MLP hidden layer topology'),
('ml_max_iterations',1200,NULL,'iterations','Maximum MLP training iterations'),
('ml_random_seed',42,NULL,'seed','Reproducible model seed'),
('ml_validation_fraction',0.2,NULL,'ratio','Held-out validation fraction'),
('source_hash_max_mb',2048,NULL,'MB','Largest source file eligible for SHA-256')
ON CONFLICT(setting_key) DO UPDATE SET
value_numeric=excluded.value_numeric,value_text=excluded.value_text,unit=excluded.unit,
description=excluded.description,updated_at=CURRENT_TIMESTAMP;

INSERT INTO pms_variable_definitions
(canonical_name,category,data_type,unit,description,valid_min,valid_max,aggregation_method,current_value_method,definition_source) VALUES
('iri_m_per_km','condition','REAL','m/km','International Roughness Index',0,30,'weighted mean','observed or ML projected','pms_variables.sql'),
('rut_depth_mm','condition','REAL','mm','Mean wheel-path rut depth',0,100,'weighted mean','observed or ML projected','pms_variables.sql'),
('vci','condition','REAL','index','Visual Condition Index',0,100,'weighted mean','observed or ML projected','pms_variables.sql'),
('pci','condition','REAL','index','Pavement Condition Index',0,100,'weighted mean','observed or ML projected','pms_variables.sql'),
('cracking_percent','condition','REAL','%','Cracked pavement area',0,100,'weighted mean','observed or ML projected','pms_variables.sql'),
('potholes_value','condition','REAL','count/km','Normalized pothole density',0,NULL,'mean','latest observation','pms_variables.sql'),
('condition_class','condition','TEXT',NULL,'IRI-derived condition band',NULL,NULL,'classification','pms_condition_band SQL function','pms_variables.sql'),
('length_km','inventory','REAL','km','Gazetted link length',0,NULL,'sum','latest network register','pms_variables.sql'),
('pavement_age_years','inventory','REAL','years','Age since construction or rehabilitation',0,200,'latest','reporting year minus intervention year','pms_variables.sql'),
('surface_type','inventory','TEXT',NULL,'Paved or unpaved surface classification',NULL,NULL,'latest','latest network register','pms_variables.sql'),
('aadt','traffic','REAL','vehicles/day','Annual average daily traffic',0,NULL,'latest','traffic station cross-link','pms_variables.sql'),
('heavy_vehicle_percent','traffic','REAL','%','Heavy vehicle share',0,100,'weighted mean','traffic station cross-link','pms_variables.sql'),
('rainfall_mm_year','climate','REAL','mm/year','Annual rainfall exposure',0,6000,'mean','regional climate cross-link','pms_variables.sql'),
('predicted_iri','model_output','REAL','m/km','Forecast IRI at target year',0,30,'prediction','ML model or deterministic fallback','pms_variables.sql'),
('prediction_confidence','model_output','REAL','ratio','Prediction confidence',0,1,'minimum','age-decayed model confidence','pms_variables.sql'),
('intervention_type','decision','TEXT',NULL,'Recommended maintenance intervention',NULL,NULL,'classification','pms_intervention SQL function','pms_variables.sql'),
('priority_score','decision','REAL','score','Network intervention priority score',0,100,'maximum','pms_priority_score SQL function','pms_variables.sql'),
('fwd_station_km','structural','REAL','km','FWD test station chainage',0,NULL,'source observation','latest FWD survey','pms_variables.sql'),
('fwd_load_kn','structural','REAL','kN','Applied FWD impulse load',0,NULL,'mean','source observation','pms_variables.sql'),
('fwd_deflection_microns','structural','REAL','µm','FWD sensor deflection response',0,NULL,'mean by sensor offset','source observation','pms_variables.sql')
ON CONFLICT(canonical_name) DO UPDATE SET
category=excluded.category,data_type=excluded.data_type,unit=excluded.unit,
description=excluded.description,valid_min=excluded.valid_min,valid_max=excluded.valid_max,
aggregation_method=excluded.aggregation_method,current_value_method=excluded.current_value_method,
definition_source=excluded.definition_source;

INSERT INTO pms_parser_variables
(parser_name,variable_name,data_type,value_numeric,value_text,unit,description) VALUES
('kuab_fwd','header_prefixes','TEXT',NULL,'H,I',NULL,'Line prefixes containing header variables'),
('kuab_fwd','data_prefix','TEXT',NULL,'D',NULL,'Measurement row prefix'),
('kuab_fwd','sensor_distance_header','TEXT',NULL,'ISensor Distance',NULL,'Sensor-offset header prefix'),
('kuab_fwd','station_index','INTEGER',1,NULL,'column','Station position in a split measurement row'),
('kuab_fwd','drop_index','INTEGER',2,NULL,'column','Drop number position'),
('kuab_fwd','load_index','INTEGER',3,NULL,'column','Applied load position'),
('kuab_fwd','deflection_start_index','INTEGER',4,NULL,'column','First deflection position'),
('kuab_fwd','deflection_end_index','INTEGER',11,NULL,'column','Exclusive final deflection position'),
('kuab_fwd','air_temperature_index','INTEGER',11,NULL,'column','Air-temperature position'),
('kuab_fwd','pavement_temperature_index','INTEGER',12,NULL,'column','Pavement-temperature position'),
('kuab_fwd','latitude_index','INTEGER',13,NULL,'column','Latitude position'),
('kuab_fwd','longitude_index','INTEGER',14,NULL,'column','Longitude position'),
('kuab_fwd','time_index','INTEGER',15,NULL,'column','Test-time position'),
('kuab_fwd','minimum_columns','INTEGER',16,NULL,'columns','Minimum valid measurement width'),
('kuab_fwd','station_m_per_km','REAL',1000,NULL,'m/km','Station conversion divisor'),
('kuab_fwd','centimetres_to_mm','REAL',10,NULL,'mm/cm','Plate and sensor conversion factor'),
('kuab_fwd','latitude_degree_digits','INTEGER',2,NULL,'digits','Latitude degrees width in DDMM coordinates'),
('kuab_fwd','longitude_degree_digits','INTEGER',3,NULL,'digits','Longitude degrees width in DDDMM coordinates'),
('kuab_fwd','minutes_per_degree','REAL',60,NULL,'minutes/degree','Coordinate conversion divisor'),
('kuab_fwd','air_temperature_min_c','REAL',-80,NULL,'°C','Lowest accepted air temperature'),
('kuab_fwd','air_temperature_max_c','REAL',80,NULL,'°C','Highest accepted air temperature'),
('kuab_fwd','pavement_temperature_min_c','REAL',-80,NULL,'°C','Lowest accepted pavement temperature'),
('kuab_fwd','pavement_temperature_max_c','REAL',100,NULL,'°C','Highest accepted pavement temperature'),
('kuab_fwd','file_format','TEXT',NULL,'KUAB FWD',NULL,'Published source-format label'),
('dynatest_f25','file_format','TEXT',NULL,'Dynatest F25',NULL,'Published source-format label'),
('dynatest_f25','tag_version','TEXT',NULL,'5001',NULL,'Version header tag'),
('dynatest_f25','tag_created','TEXT',NULL,'5011',NULL,'Creation-date header tag'),
('dynatest_f25','tag_sensor_offsets','TEXT',NULL,'5020',NULL,'Plate and sensor offsets tag'),
('dynatest_f25','tag_operator','TEXT',NULL,'5030',NULL,'Operator tag'),
('dynatest_f25','tag_project','TEXT',NULL,'5031',NULL,'Project metadata tag'),
('dynatest_f25','tag_road','TEXT',NULL,'5032',NULL,'Road metadata tag'),
('dynatest_f25','tag_station','TEXT',NULL,'5301',NULL,'Station metadata tag'),
('dynatest_f25','tag_comment','TEXT',NULL,'5302',NULL,'Comment tag'),
('dynatest_f25','tag_temperature','TEXT',NULL,'5303',NULL,'Temperature tag'),
('dynatest_f25','version_index','INTEGER',1,NULL,'column','Version value position'),
('dynatest_f25','created_year_index','INTEGER',3,NULL,'column','Creation year position'),
('dynatest_f25','created_month_index','INTEGER',4,NULL,'column','Creation month position'),
('dynatest_f25','created_day_index','INTEGER',5,NULL,'column','Creation day position'),
('dynatest_f25','created_minimum_columns','INTEGER',7,NULL,'columns','Minimum creation row width'),
('dynatest_f25','plate_radius_index','INTEGER',1,NULL,'column','Plate radius position'),
('dynatest_f25','sensor_offsets_start_index','INTEGER',2,NULL,'column','First sensor offset position'),
('dynatest_f25','operator_index','INTEGER',1,NULL,'column','Operator value position'),
('dynatest_f25','project_name_index','INTEGER',1,NULL,'column','Project name position'),
('dynatest_f25','road_code_index','INTEGER',2,NULL,'column','Road code position'),
('dynatest_f25','surface_type_index','INTEGER',4,NULL,'column','Surface type position'),
('dynatest_f25','road_name_index','INTEGER',1,NULL,'column','Road name position'),
('dynatest_f25','start_chainage_index','INTEGER',3,NULL,'column','Start chainage position'),
('dynatest_f25','end_chainage_index','INTEGER',4,NULL,'column','End chainage position'),
('dynatest_f25','station_minimum_columns','INTEGER',14,NULL,'columns','Minimum station row width'),
('dynatest_f25','station_index','INTEGER',5,NULL,'column','Station chainage position'),
('dynatest_f25','lane_index','INTEGER',8,NULL,'column','Lane position'),
('dynatest_f25','test_year_index','INTEGER',9,NULL,'column','Test year position'),
('dynatest_f25','test_month_index','INTEGER',10,NULL,'column','Test month position'),
('dynatest_f25','test_day_index','INTEGER',11,NULL,'column','Test day position'),
('dynatest_f25','test_hour_index','INTEGER',12,NULL,'column','Test hour position'),
('dynatest_f25','test_minute_index','INTEGER',13,NULL,'column','Test minute position'),
('dynatest_f25','comment_minimum_columns','INTEGER',11,NULL,'columns','Minimum comment row width'),
('dynatest_f25','comment_index','INTEGER',10,NULL,'column','Comment value position'),
('dynatest_f25','temperature_minimum_columns','INTEGER',5,NULL,'columns','Minimum temperature row width'),
('dynatest_f25','air_temperature_index','INTEGER',3,NULL,'column','Air temperature position'),
('dynatest_f25','pavement_temperature_index','INTEGER',4,NULL,'column','Pavement temperature position'),
('dynatest_f25','pressure_index','INTEGER',1,NULL,'column','Plate pressure position'),
('dynatest_f25','deflections_start_index','INTEGER',2,NULL,'column','First deflection position'),
('dynatest_f25','default_plate_radius_mm','REAL',150,NULL,'mm','Plate radius used when absent'),
('dynatest_f25','millimetres_per_metre','REAL',1000,NULL,'mm/m','Radius conversion divisor'),
('dynatest_f25','minimum_drop_number','INTEGER',1,NULL,'drop','First accepted drop number'),
('dynatest_f25','maximum_drop_number','INTEGER',9,NULL,'drop','Last accepted drop number'),
('dynatest_f25','minimum_drop_columns','INTEGER',4,NULL,'columns','Minimum valid drop width')
ON CONFLICT(parser_name,variable_name) DO UPDATE SET
data_type=excluded.data_type,value_numeric=excluded.value_numeric,value_text=excluded.value_text,
unit=excluded.unit,description=excluded.description,updated_at=CURRENT_TIMESTAMP;

INSERT INTO pms_ingestion_formats
(repository_group,extension,parser_name,content_signature,ingestion_mode,description) VALUES
('fwd','.f25','dynatest_f25','', 'structured','Dynatest F25 structural measurement file'),
('fwd','.fwd','kuab_fwd','', 'structured','KUAB FWD structural measurement file'),
('fwd','.txt','kuab_fwd','fwd file','signature','KUAB FWD text export'),
('fwd','.gpx','gpx','', 'spatial','GPS route or track file'),
('fwd','.zip','zip_catalog','', 'catalog','ZIP archive entry inventory'),
('fwd','.csv','csv','', 'tabular','Delimited tabular source'),
('fwd','.xlsx','excel','', 'tabular','Excel workbook metadata and recognized rows'),
('fwd','.pdf','document','', 'document','Searchable PDF document'),
('fwd','.docx','document','', 'document','Searchable Word document'),
('fwd','.mdb','access','', 'tabular','Microsoft Access table and field metadata'),
('fwd','.accdb','access','', 'tabular','Microsoft Access table and field metadata')
ON CONFLICT(repository_group,extension,content_signature) DO UPDATE SET
parser_name=excluded.parser_name,ingestion_mode=excluded.ingestion_mode,description=excluded.description;
