begin;

create table if not exists public.pms_engine_settings (
  setting_key text primary key,
  value_numeric double precision,
  value_text text,
  unit text,
  description text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.pms_source_files (
  source_id bigint generated by default as identity primary key,
  repository_group text not null,
  absolute_path text not null unique,
  relative_path text not null,
  file_name text not null,
  extension text not null,
  byte_size bigint not null,
  modified_at timestamptz not null,
  content_sha256 text,
  ingestion_status text not null default 'registered',
  record_count bigint not null default 0,
  error_message text,
  registered_at timestamptz not null default now(),
  ingested_at timestamptz
);

create table if not exists public.pms_source_tables (
  source_table_id bigint generated by default as identity primary key,
  source_id bigint not null references public.pms_source_files(source_id) on delete cascade,
  table_name text not null,
  table_kind text not null,
  header_row integer,
  row_count bigint not null default 0,
  column_count integer not null default 0,
  unique(source_id, table_name)
);

create table if not exists public.pms_variable_definitions (
  variable_id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  category text not null,
  data_type text not null,
  unit text,
  description text not null,
  valid_min double precision,
  valid_max double precision,
  aggregation_method text,
  current_value_method text not null,
  definition_source text not null
);

create table if not exists public.pms_source_fields (
  source_field_id bigint generated by default as identity primary key,
  source_table_id bigint not null references public.pms_source_tables(source_table_id) on delete cascade,
  ordinal_position integer not null,
  source_name text not null,
  canonical_name text,
  inferred_type text,
  unit text,
  non_null_count bigint,
  unique(source_table_id, ordinal_position)
);

create table if not exists public.pms_manual_documents (
  manual_id bigint generated by default as identity primary key,
  source_id bigint not null unique references public.pms_source_files(source_id) on delete cascade,
  title text not null,
  document_type text not null,
  page_count integer,
  extracted_character_count bigint not null default 0,
  searchable_text text,
  indexed_at timestamptz not null default now()
);

create table if not exists public.pms_road_links (
  link_id text primary key,
  road_no text,
  road_class text,
  link_name text,
  chainage_from_km double precision,
  chainage_to_km double precision,
  length_km double precision,
  surface_type text,
  maintenance_station text,
  maintenance_region text,
  completion_year integer,
  rehabilitation_year integer,
  pavement_age_years double precision,
  source_id bigint references public.pms_source_files(source_id),
  updated_at timestamptz not null default now()
);

create table if not exists public.pms_condition_observations (
  observation_id bigint generated by default as identity primary key,
  source_id bigint not null references public.pms_source_files(source_id),
  source_table_id bigint references public.pms_source_tables(source_table_id),
  source_row_number bigint,
  link_id text references public.pms_road_links(link_id),
  survey_date date,
  survey_year integer,
  chainage_from_km double precision,
  chainage_to_km double precision,
  iri_m_per_km double precision,
  rut_depth_mm double precision,
  vci double precision,
  pci double precision,
  cracking_percent double precision,
  potholes_value double precision,
  condition_class text,
  data_quality text not null default 'source',
  raw_values_json jsonb,
  unique(source_id, source_table_id, source_row_number)
);

create table if not exists public.pms_inventory_assets (
  inventory_asset_id bigint generated by default as identity primary key,
  source_id bigint not null references public.pms_source_files(source_id),
  source_table_id bigint references public.pms_source_tables(source_table_id),
  source_row_number bigint,
  external_id text,
  link_id text references public.pms_road_links(link_id),
  asset_type text not null,
  asset_subtype text,
  chainage_from_km double precision,
  chainage_to_km double precision,
  longitude double precision,
  latitude double precision,
  quantity double precision,
  length_m double precision,
  width_m double precision,
  condition_class text,
  survey_date date,
  raw_values_json jsonb,
  unique(source_id, source_table_id, source_row_number)
);

create table if not exists public.pms_model_runs (
  model_run_id bigint generated by default as identity primary key,
  model_name text not null,
  model_version text not null,
  algorithm text not null,
  feature_variables_json jsonb not null,
  target_variables_json jsonb not null,
  hyperparameters_json jsonb not null,
  training_rows bigint not null,
  validation_metrics_json jsonb not null,
  trained_at timestamptz not null,
  reporting_at date not null,
  artifact_path text,
  status text not null
);

create table if not exists public.pms_current_values (
  link_id text not null references public.pms_road_links(link_id) on delete cascade,
  variable_id bigint not null references public.pms_variable_definitions(variable_id),
  value_numeric double precision,
  value_text text,
  reporting_at date not null,
  observed_at timestamptz,
  value_method text not null,
  confidence double precision not null check(confidence between 0 and 1),
  source_id bigint references public.pms_source_files(source_id),
  model_run_id bigint references public.pms_model_runs(model_run_id),
  primary key(link_id, variable_id)
);

create table if not exists public.pms_predictions (
  prediction_id bigint generated by default as identity primary key,
  link_id text not null references public.pms_road_links(link_id) on delete cascade,
  model_run_id bigint not null references public.pms_model_runs(model_run_id),
  prediction_year integer not null,
  iri_m_per_km double precision,
  condition_class text,
  intervention_type text,
  intervention_year integer,
  confidence double precision not null check(confidence between 0 and 1),
  unique(link_id, model_run_id, prediction_year)
);

create table if not exists public.pms_infographics (
  infographic_id text primary key,
  sort_order integer not null unique,
  title text not null,
  subtitle text,
  visualization_type text not null,
  unit text,
  payload_json jsonb not null,
  sql_query_name text not null,
  generated_at timestamptz not null
);

create table if not exists public.pms_parser_variables (
  parser_name text not null,
  variable_name text not null,
  data_type text not null check(data_type in ('INTEGER','REAL','TEXT','BOOLEAN')),
  value_numeric double precision,
  value_text text,
  unit text,
  description text not null,
  updated_at timestamptz not null default now(),
  primary key(parser_name, variable_name),
  check(value_numeric is not null or value_text is not null)
);

create table if not exists public.pms_ingestion_formats (
  repository_group text not null,
  extension text not null,
  parser_name text,
  content_signature text not null default '',
  ingestion_mode text not null,
  description text not null,
  primary key(repository_group, extension, content_signature)
);

create table if not exists public.pms_fwd_surveys (
  fwd_survey_id bigint generated by default as identity primary key,
  source_id bigint not null unique references public.pms_source_files(source_id) on delete cascade,
  project_name text,
  road_name text,
  road_code text,
  operator_name text,
  lane text,
  weather text,
  surface_type text,
  survey_date date,
  file_format text not null,
  file_version text,
  plate_radius_mm double precision,
  nominal_load_kn double precision,
  sensor_offsets_mm_json jsonb,
  start_chainage_km double precision,
  end_chainage_km double precision,
  notes text,
  raw_header_json jsonb,
  imported_at timestamptz not null default now()
);

create table if not exists public.pms_fwd_tests (
  fwd_test_id bigint generated by default as identity primary key,
  fwd_survey_id bigint not null references public.pms_fwd_surveys(fwd_survey_id) on delete cascade,
  source_row_number bigint not null,
  station_km double precision,
  drop_number integer,
  load_kn double precision,
  air_temperature_c double precision,
  pavement_temperature_c double precision,
  latitude double precision,
  longitude double precision,
  tested_at timestamptz,
  comment text,
  data_quality text not null default 'source',
  raw_values_json jsonb,
  unique(fwd_survey_id, source_row_number, drop_number)
);

create table if not exists public.pms_fwd_deflections (
  fwd_test_id bigint not null references public.pms_fwd_tests(fwd_test_id) on delete cascade,
  sensor_index integer not null,
  sensor_offset_mm double precision,
  deflection_microns double precision not null,
  primary key(fwd_test_id, sensor_index)
);

create table if not exists public.pms_source_gps_points (
  gps_point_id bigint generated by default as identity primary key,
  source_id bigint not null references public.pms_source_files(source_id) on delete cascade,
  sequence_number bigint not null,
  route_name text,
  latitude double precision not null,
  longitude double precision not null,
  elevation_m double precision,
  recorded_at timestamptz,
  unique(source_id, sequence_number)
);

create table if not exists public.pms_archive_entries (
  archive_entry_id bigint generated by default as identity primary key,
  source_id bigint not null references public.pms_source_files(source_id) on delete cascade,
  entry_path text not null,
  byte_size bigint not null default 0,
  compressed_size bigint not null default 0,
  modified_at timestamptz,
  crc32 text,
  unique(source_id, entry_path)
);

create table if not exists public.pms_ml_training_rows (
  training_row_id bigint generated by default as identity primary key,
  link_id text not null references public.pms_road_links(link_id) on delete cascade,
  current_iri double precision not null check(current_iri between 0 and 30),
  rut_depth_mm double precision not null default 0 check(rut_depth_mm between 0 and 100),
  cracking_percent double precision not null default 0 check(cracking_percent between 0 and 100),
  pavement_age_years double precision not null default 0 check(pavement_age_years between 0 and 200),
  length_km double precision not null default 1 check(length_km > 0),
  aadt double precision not null default 0 check(aadt >= 0),
  years_ahead integer not null check(years_ahead > 0),
  surface_type text not null default 'Unknown',
  maintenance_region text not null default 'Unknown',
  target_iri double precision not null check(target_iri between 0 and 30),
  source_observation_id bigint references public.pms_condition_observations(observation_id),
  target_observation_id bigint references public.pms_condition_observations(observation_id),
  created_at timestamptz not null default now(),
  unique(source_observation_id, target_observation_id)
);

create table if not exists public.pms_prediction_requests (
  request_id bigint generated by default as identity primary key,
  link_id text not null,
  target_year integer not null,
  input_json jsonb not null,
  output_json jsonb not null,
  model_version text,
  requested_by text,
  requested_at timestamptz not null default now()
);

create index if not exists idx_pms_sources_group on public.pms_source_files(repository_group, extension);
create index if not exists idx_pms_source_fields_name on public.pms_source_fields(canonical_name);
create index if not exists idx_pms_condition_link_year on public.pms_condition_observations(link_id, survey_year);
create index if not exists idx_pms_inventory_link_type on public.pms_inventory_assets(link_id, asset_type);
create index if not exists idx_pms_fwd_survey_date on public.pms_fwd_surveys(survey_date, road_code);
create index if not exists idx_pms_fwd_test_station on public.pms_fwd_tests(fwd_survey_id, station_km);
create index if not exists idx_pms_fwd_test_location on public.pms_fwd_tests(latitude, longitude);
create index if not exists idx_pms_gps_source on public.pms_source_gps_points(source_id, sequence_number);
create index if not exists idx_pms_current_variable on public.pms_current_values(variable_id, value_method);
create index if not exists idx_pms_training_link on public.pms_ml_training_rows(link_id, years_ahead);
create index if not exists idx_pms_prediction_request_link on public.pms_prediction_requests(link_id, target_year);

commit;
