apiVersion: v1
kind: Service
metadata:
  name: npms-backend
  namespace: npms
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: npms-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
